# Generated by Django 3.1.2 on 2020-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201021_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(help_text='Excerpt', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='longDescr',
            field=models.CharField(blank=True, help_text='Description', max_length=600),
        ),
    ]
