# Generated by Django 3.1.2 on 2020-10-27 09:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201026_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='longDescr',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('limited', 'limited'), ('unlimited', 'unlimited')], default='unlimited', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='app/static/images', validators=[app.models.image_extension]),
        ),
    ]
