# Generated by Django 3.1.2 on 2020-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201027_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Description', max_length=600, verbose_name='Description'),
        ),
    ]
